using System;
using System.Collections.Generic;
using System.Text;

namespace LockerManagementSystem
{
    public enum LockerSize
    {
        Small,
        Medium,
        Large,
        XtraLarge
    }
    /// <summary>
    /// This is a TravelLockerManagementSystem
    /// where user can drop and pick luggage from it
    /// </summary>
    public class Locker
    {
        //Declaring variable
        private static int lastLockerID = 0;
               
        #region Properties

        /// <summary>
        /// defines email address of the user
        /// </summary>
        public string  EmailAddress { get; set; }

        
        /// <summary>
        /// defines size of locker(small/medium/large)
        /// </summary>
        public LockerSize LockerSize { get; set; }

        /// <summary>
        /// defines autogenerated locker number for locker
        /// </summary>
        public int LockerID { get;  }

        /// <summary>
        /// defines creation date and time for locker
        /// this should be created by owner so the set property is private
        /// </summary>
        public DateTime CheckInDate { get; set; }

        /// <summary>
        /// defines the number of hours user need that locker for
        /// </summary>
        public int Duration { get; set; }

        
        /// <summary>
        /// defines the total number of lockers needed for luggage storage
        /// </summary>
        public int NumberOfLockers { get; set; }

        /// <summary>
        /// Defines price of a locker
        /// </summary>
        
        public int Price { get; set; }
        #endregion
        #region Constructors        
        public Locker()
        {
            /// <summary>
            /// Automatic generation of date at the construction time
            /// </summary>
            CheckInDate = DateTime.Now;

            /// <summary>
            /// Generating locker number
            /// </summary>
            LockerID = ++lastLockerID;

            /// <summary>
            /// Generating number of hours to store luggage
            /// </summary>


        }
        #endregion
        #region Methods
        /// <summary>
        /// Deposit luggage into the locker
        /// </summary>
        /// <param name="Bag"></param>
        public void Drop(string Bag)
        {
        }

        public void Pick(string Bag)
        {
        }
        #endregion

       
    }
}
