// <auto-generated />
using System;
using LockerManagementSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LockerManagementSystem.Migrations
{
    [DbContext(typeof(LockerContext))]
    [Migration("20191122073905_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LockerManagementSystem.Locker", b =>
                {
                    b.Property<int>("LockerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckInDate");

                    b.Property<string>("EmailAddress");

                    b.Property<int>("LockerSize");

                    b.Property<bool>("Paid");

                    b.HasKey("LockerID")
                        .HasName("PK_Lockers");

                    b.ToTable("Lockers");
                });
#pragma warning restore 612, 618
        }
    }
}
